coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 90%
        threshold: 5%

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: true

