name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is this bug related to?
      options:
        - "@spekra/playwright"
        - "Other / Not sure"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Configure reporter with...
        2. Run tests with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your reporter configuration (remove any sensitive values like API keys)
      render: typescript
      placeholder: |
        // playwright.config.ts
        reporter: [
          ['@spekra/playwright', { ... }],
        ],

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide environment details:
      value: |
        - OS: 
        - Node.js version: 
        - Package version: 
        - Playwright version: 
        - CI environment (if applicable): 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please include any relevant log output (use `debug: true` for verbose logs)
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues that describe this problem
          required: true
        - label: I have enabled `debug: true` and included relevant logs
          required: false
